import { ConvexHttpClient } from "convex/browser";
import { api } from "../../convex/_generated/api";
import { savePrivateKeyToIndexedDB } from "../utils/cryptoBridge";

const CONVEX_URL =
  (import.meta.env?.VITE_CONVEX_URL as string) ||
  "https://rightful-orca-265.convex.cloud";

const convexClient = new ConvexHttpClient(CONVEX_URL);
const convexApi = api as any;

/**
 * Programmatically registers a SHA-256 hash to Hyperledger Besu via Convex server action
 * @param messageHash The raw 64-character SHA-256 hex string generated by the client
 */
export async function logHashToBlockchain(
  messageHash: string,
): Promise<string> {
  try {
    const cleanHash = messageHash.startsWith("0x")
      ? messageHash
      : `0x${messageHash}`;

    console.log(`📡 Dispatching hash registration via Convex: ${cleanHash}`);

    const result: any = await convexClient.action(convexApi.blockchainActions.recordMessage, {
      messageId: `qa-hash-${Date.now()}`,
      content: cleanHash,
    });

    if (result && !result.success) {
      console.warn("❌ Non-critical notice logging hash to Hyperledger Besu:", result.error);
      return result.txHash || "";
    }

    console.log("🚀 Ledger updated! Transaction Hash:", result?.txHash);
    return result?.txHash || "";
  } catch (error) {
    console.error(
      "❌ Failed to log authentication hash to Hyperledger Besu:",
      error,
    );
    throw error;
  }
}

/**
 * Natively generates a secure asymmetric keypair inside the browser context
 * Returns the exportable public key string to anchor to the database profile
 */
export async function generateClientIdentityKeys(userId?: string): Promise<string> {
  if (!window.crypto || !window.crypto.subtle) {
    throw new Error("Web Crypto API is unavailable. Ensure your origin is running on http://localhost.");
  }

  // 1. Generate an asymmetric RSA-OAEP cryptographic engine block
  const keyPair = await window.crypto.subtle.generateKey(
    {
      name: "RSA-OAEP",
      modulusLength: 2048,
      publicExponent: new Uint8Array([1, 0, 1]), // Standard 65537 exponent configuration
      hash: "SHA-256",
    },
    true,
    ["encrypt", "decrypt"]
  );

  // 2. Export the public key as a portable string block format (SubjectPublicKeyInfo Base64)
  const exportedPublicRaw = await window.crypto.subtle.exportKey("spki", keyPair.publicKey);
  const base64PublicKey = btoa(String.fromCharCode(...new Uint8Array(exportedPublicRaw)));

  // 3. SECURELY save the Private Key into IndexedDB for the active user
  const targetUserId = userId || localStorage.getItem("qchat_active_user_id");
  if (targetUserId) {
    await savePrivateKeyToIndexedDB(targetUserId, keyPair.privateKey);
  }

  return base64PublicKey;
}
